const OutletData = [
    {
      partyCode:'1',
      ownerName:'Harsh',
      ledgerName:'HD Corporate hub',
      outletType:'Producers',
      classOfOutlet:'A++',
      whatsappNumber:'9691495822',
      mobileNumber:'9691495822',
      permanentRemark:'Biggest Producer',
      temporaryRemark:'Excellent-Sales',
      areaName:'Patan' ,
      beatName:'Nunser',
      birthday:'08/05/2002', 
      aniversary:'12/12/2025',
      imageUrl:'https://lh3.googleusercontent.com/a/AAcHTtfVyuHnbIXZftk_8UKlKa1KFGbB5P5efUvWYS-zlAYly65C6ZhWkJ-Me8f-5wnevvGpQsa1IK0SJXkXU5ptFWr6TZo=s360-c-no',
      status:'true',
    
    },
    {
        partyCode: 'P001',
        ownerName: 'John Doe',
        ledgerName: 'Ledger ABC',
        outletType: 'Retail',
        classOfOutlet: 'A',
        whatsappNumber: '9876543210',
        mobileNumber: '9876543210',
        permanentRemark: 'Giant',
        temporaryRemark: 'Stock full',
        areaName: 'Panagar',
        beatName: 'Panagar 3',
        birthday: '01/01/1990',
        aniversary: '01/01/2010',
        status:'True',
      },
       
    {
      partyCode: 'P002',
      ownerName: 'Jane Smith',
      ledgerName: 'Ledger XYZ',
      outletType: 'Wholesale',
      classOfOutlet: 'B',
      whatsappNumber: '9876543211',
      mobileNumber: '9876543211',
      permanentRemark: 'Small Shop',
      temporaryRemark: 'Limited stock',
      areaName: 'City Center',
      beatName: 'City Center East',
      birthday: '01/01/1991',
      aniversary: '01/01/2012',
      status:'false',
    },
    // Additional outlet data
    {
      partyCode: 'P003',
      ownerName: 'Michael Johnson',
      ledgerName: 'Ledger MNO',
      outletType: 'Retail',
      classOfOutlet: 'C',
      whatsappNumber: '9876543212',
      mobileNumber: '9876543212',
      permanentRemark: 'Newly Opened',
      temporaryRemark: 'Promotions',
      areaName: 'Downtown',
      beatName: 'Downtown West',
      birthday: '01/01/1989',
      aniversary: '01/01/2013',
      imageUrl: 'https://img.freepik.com/free-photo/3d-cartoon-shop-keeper-character_1048-16762.jpg?w=1060&t=st=1692188835~exp=1692189435~hmac=66eb6706a7919e21ae84750f3d75e4fc42c897825554993dcc588bdbe3bd3894',
      status:'true',
    },
    {
      partyCode: 'P004',
      ownerName: 'Sarah Lee',
      ledgerName: 'Ledger ABC',
      outletType: 'Retail',
      classOfOutlet: 'B',
      whatsappNumber: '9876543213',
      mobileNumber: '9876543213',
      permanentRemark: 'High Footfall',
      temporaryRemark: 'Seasonal Sales',
      areaName: 'Suburbia',
      beatName: 'Suburbia North',
      birthday: '01/01/1990',
      aniversary: '01/01/2020',
      status:'false',
  
    },
    {
      partyCode: 'P005',
      ownerName: 'David Williams',
      ledgerName: 'Ledger XYZ',
      outletType: 'Wholesale',
      classOfOutlet: 'A',
      whatsappNumber: '9876543214',
      mobileNumber: '9876543214',
      permanentRemark: 'Large Inventory',
      temporaryRemark: 'Bulk Discounts',
      areaName: 'Industrial Zone',
      beatName: 'Industrial Zone South',
      birthday: '01/01/1990',
      aniversary: '01/01/2023',
      status:'false',
  
    },
    {
      partyCode: 'P006',
      ownerName: 'Emma Johnson',
      ledgerName: 'Ledger EFG',
      outletType: 'Retail',
      classOfOutlet: 'A',
      whatsappNumber: '9876543215',
      mobileNumber: '9876543215',
      permanentRemark: 'Popular Brand',
      temporaryRemark: 'New Collection',
      areaName: 'Mall Area',
      beatName: 'Mall West',
      birthday: '01/01/1992',
      aniversary: '01/01/2015',
      status:'true',
  
    },
    {
      partyCode: 'P007',
      ownerName: 'Michael Brown',
      ledgerName: 'Ledger MNO',
      outletType: 'Wholesale',
      classOfOutlet: 'B',
      whatsappNumber: '9876543216',
      mobileNumber: '9876543216',
      permanentRemark: 'Bulk Purchases',
      temporaryRemark: 'Year-End Sale',
      areaName: 'Commercial District',
      beatName: 'Commercial East',
      birthday: '01/01/1988',
      aniversary: '01/01/2011',
      status:'false',
  
    },
    {
      partyCode: 'P008',
      ownerName: 'Sophia Miller',
      ledgerName: 'Ledger ABC',
      outletType: 'Retail',
      classOfOutlet: 'C',
      whatsappNumber: '9876543217',
      mobileNumber: '9876543217',
      permanentRemark: 'Fashion Boutique',
      temporaryRemark: 'Fashion Show',
      areaName: 'Fashion Street',
      beatName: 'Fashion North',
      birthday: '01/01/1995',
      aniversary: '01/01/2018',
      status:'true',
    },
    {
      partyCode: 'P009',
      ownerName: 'William Jones',
      ledgerName: 'Ledger XYZ',
      outletType: 'Retail',
      classOfOutlet: 'B',
      whatsappNumber: '9876543218',
      mobileNumber: '9876543218',
      permanentRemark: 'High-end Products',
      temporaryRemark: 'VIP Sale',
      areaName: 'Luxury Zone',
      beatName: 'Luxury East',
      birthday: '01/01/1993',
      aniversary: '01/01/2017',
      status:'true',
    },
    {
      partyCode: 'P010',
      ownerName: 'Olivia Davis',
      ledgerName: 'Ledger EFG',
      outletType: 'Wholesale',
      classOfOutlet: 'A',
      whatsappNumber: '9876543219',
      mobileNumber: '9876543219',
      permanentRemark: 'Large Orders',
      temporaryRemark: 'Bulk Discounts',
      areaName: 'Industrial Hub',
      beatName: 'Industrial North',
      birthday: '01/01/1991',
      aniversary: '01/01/2022',
      imageUrl:'https://torrent4you.org/wp-content/uploads/marvels-spider-man-remastered-330x140.jpg',
      status:'false',
    },{
      partyCode: 'P011',
      ownerName: 'Peter Smith',
      ledgerName: 'Ledger XYZ',
      outletType: 'Retail',
      classOfOutlet: 'C',
      whatsappNumber: '9876543220',
      mobileNumber: '9876543220',
      permanentRemark: 'Newly Opened',
      temporaryRemark: 'Freebies',
      areaName: 'Marketplace',
      beatName: 'Marketplace East',
      birthday: '01/01/1996',
      aniversary: '01/01/2021',
      imageUrl: 'https://miro.medium.com/max/1400/1*35g8n04a27z9X7e6f4v5ZQ.jpeg',
      status: 'true'
    },
    {
      partyCode: 'P012',
      ownerName: 'Amelia Williams',
      ledgerName: 'Ledger MNO',
      outletType: 'Wholesale',
      classOfOutlet: 'B',
      whatsappNumber: '9876543221',
      mobileNumber: '9876543221',
      permanentRemark: 'Discount Offers',
      temporaryRemark: 'Back to School Sale',
      areaName: 'Educational Zone',
      beatName: 'Educational West',
      birthday: '01/01/1994',
      aniversary: '01/01/2019',
      status: 'true'
    },
    {
      partyCode: 'P013',
      ownerName: 'Thomas Brown',
      ledgerName: 'Ledger ABC',
      outletType: 'Retail',
      classOfOutlet: 'A',
      whatsappNumber: '9876543222',
      mobileNumber: '9876543222',
      permanentRemark: 'Family-owned Business',
      temporaryRemark: 'Grand Opening',
      areaName: 'Neighborhood',
      beatName: 'Neighborhood North',
      birthday: '01/01/1997',
      aniversary: '01/01/2024',
      imageUrl: 'https://miro.medium.com/max/2000/1*8iDc18y6h1X4-Y_o4n885g.jpeg',
      status: 'true'
    },
    {
      partyCode: 'P014',
      ownerName: 'Elizabeth Johnson',
      ledgerName: 'Ledger EFG',
      outletType: 'Wholesale',
      classOfOutlet: 'C',
      whatsappNumber: '9876543223',
      mobileNumber: '9876543223',
      permanentRemark: 'Locally Sourced Products',
      temporaryRemark: 'Farmers Market',
      areaName: 'Farmers Market',
      beatName: 'Farmers Market East',
      birthday: '01/01/1998',
      aniversary: '01/01/2025',
      status: 'true'
    },{
      partyCode: 'P016',
      ownerName: 'Emily Jones',
      ledgerName: 'Ledger ABC',
      outletType: 'Wholesale',
      classOfOutlet: 'B',
      whatsappNumber: '9876543225',
      mobileNumber: '9876543225',
      permanentRemark: 'Online Shopping',
      temporaryRemark: 'Free Shipping',
      areaName: 'Online Zone',
      beatName: 'Online West',
      birthday: '01/01/1999',
      aniversary: '01/01/2026',
      status: 'true'
    },
    {
      partyCode: 'P017',
      ownerName: 'Benjamin Davis',
      ledgerName: 'Ledger EFG',
      outletType: 'Retail',
      classOfOutlet: 'C',
      whatsappNumber: '9876543226',
      mobileNumber: '9876543226',
      permanentRemark: 'Home Appliances',
      temporaryRemark: 'Big Sale',
      areaName: 'Home Appliances Zone',
      beatName: 'Home Appliances East',
      birthday: '01/01/2000',
      aniversary: '01/01/2027',
      status: 'true'
    },
    {
      partyCode: 'P018',
      ownerName: 'Caroline Miller',
      ledgerName: 'Ledger MNO',
      outletType: 'Wholesale',
      classOfOutlet: 'A',
      whatsappNumber: '9876543227',
      mobileNumber: '9876543227',
      permanentRemark: 'Electronics',
      temporaryRemark: 'New Products',
      areaName: 'Electronics Zone',
      beatName: 'Electronics West',
      birthday: '01/01/2001',
      aniversary: '01/01/2028',
      status: 'true'
    },
    {
      partyCode: 'P019',
      ownerName: 'David Williams',
      ledgerName: 'Ledger ABC',
      outletType: 'Retail',
      classOfOutlet: 'B',
      whatsappNumber: '9876543228',
      mobileNumber: '9876543228',
      permanentRemark: 'Supermarket',
      temporaryRemark: 'Weekly Deals',
      areaName: 'Supermarket Zone',
      beatName: 'Supermarket East',
      birthday: '01/01/2002',
      aniversary: '01/01/2029',
      status: 'true'
    },
    {
      partyCode: 'P020',
      ownerName: 'Emma Brown',
      ledgerName: 'Ledger EFG',
      outletType: 'Wholesale',
      classOfOutlet: 'C',
      whatsappNumber: '9876543229',
      mobileNumber: '9876543229',
      permanentRemark: 'Grocery',
      temporaryRemark: 'End of Season Sale',
      areaName: 'Grocery Zone',
      beatName: 'Grocery West',
      birthday: '01/01/2003',
      aniversary: '01/01/2030',
      status: 'true'
    },
    // Add more outlet objects as needed
  
  
  ];
  
  export default OutletData;
  